### ISSUE TITLE
Episode detail

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/RickAndMortyCMM#10]
# Description
Create the episode detail screen

# Tasks
- [x] Create remote datasource
- [x] TDD repository
- [x] TDD use case
- [x] Create State
- [x] Create Intent
- [x] Create Effect
- [x] Create Reducer, ViewModel
- [x] Episode Detail components
- [x] Episode Detail screen
