### ISSUE TITLE
Main scaffold

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/RickAndMortyCMM#2]
# Description
Create a scaffold with a bottom nav bar with 3 items 
- Characters
- Episodes
- Locations

# Tasks
- [x] Create all bottom routes
- [x] Create an immutable list of all routes
- [x] Create MainScaffold
- [x] Pass the list as a parameter
- [x] Create a bottom navigation for now
- [x] Create the different empty screens 
- [x] Pass the scaffold to each bottom item screen
