### ISSUE TITLE
Character Detail

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/RickAndMortyCMM#4]
# Description
It should display all of the character detail

# Task
- [x] Write remote datasource
- [x] Write repository
- [x] Write use case
- [x] Create Intent, State, Effect
- [x] Create Reducer
- [x] Create title component
- [x] Create image component
- [x] Create info component
- [x] Navigate to episode detail or location detail
- [x] Create different intent and effects
- [x] Load character detail ID in view model
- [x] send get character detail id after getting the id in init
- [x] Create a list of episodes
- [x] Add effect to navigate to episode detail
- [x] Create a component with location and origin
- [x] Apple to click on location, origin, and episodes
- [x] Add effect to navigate to location detail
