### ISSUE TITLE
Episodes

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/RickAndMortyCMM#6]
# Description
Should create the episodes screen

# Tasks
- [x] Episodes remote datasource
- [x] TDD episodes repository
- [x] TDD episodes use case
- [x] Create State
- [x] Create Intent
- [x] Create Effect
- [x] Create Reducer
- [x] Create list item
- [x] Create list view
- [x] Create episodes screen
- [x] Create effect to navigate to episode detail
