### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/RickAndMortyCMM#8]
# Description
Display all the locations

# Task
- [x] Create Location Remote datasource
- [x] TDD Location repository
- [x] TDD Location use case
- [x] Create State
- [x] Create Intent
- [x] Create Effect
- [x] Create Reducer, ViewModel
- [x] Create Location List Item
- [x] Create Location List View
- [x] Create Location Content
- [x] Create Location Screen
- [x] Add intent to load more
- [x] Add effect to navigate to detail
